name: Fetch CDN URL Every 5 min

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-cdn-url:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch full API response
        run: |
          response=$(curl -s -H "Referer: https://dora-bash-live.blogspot.com/" \
            "https://proxy.animebash.workers.dev/?u=https://bashserver.xyz/fucku.php?id=496")

          echo "$response" > get.txt

          echo "Fetched full API response:"
          cat get.txt

      - name: Commit and push get.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add get.txt
          git commit -m "Update get.txt - $(date -u)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
